title: CV
google_analytics: ""
remote_theme: jekyll/minima
author:
  name: masaki ishiyama
  email: ""
plugins:
  - jekyll-remote-theme

minima:
  social_links:
  - { platform: github, user_url: "https://github.com/babarot" }
  - { platform: blog, user_url: "https://tellme.tokyo" }
  - { platform: sd, user_url: "https://speakerdec.com/babarot" }
