title: CV
google_analytics: ""
remote_theme: jekyll/minima
author:
  name: masaki ishiyama
  email: ""
plugins:
  - jekyll-remote-theme

social_links:
- { platform: github, user_url: "https://github.com/babarot" }
