title: CV
google_analytics: ""
remote_theme: jekyll/minima
author:
  name: masaki ishiyama
  email: b4b4r07@gmail.com
plugins:
  - jekyll-remote-theme

minima:
  social_links:
  - platform: blog
    user_url: https://tellme.tokyo
  - platform: github
    user_url: https://github.com/babarot
  - platform: sd
    user_url: https://speakerdeck.com/babarot
  - platform: zenn
    user_url: https://zenn.dev/babarot
  # - platform: sizume
  #   user_url: https://sizu.me/babarot
